global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "anggota-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["anggota-service:8081"]

  - job_name: "buku-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["buku-service:8082"]

  - job_name: "peminjaman-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["peminjaman-service:8083"]

  - job_name: "pengembalian-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["pengembalian-service:8084"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:9000"]
